url: "https://slotparkbonuscode.de"  # Replace with your site's URL
baseurl: ""  # Leave this empty if your site is at the root of the domain

permalink: pretty

title: Slotpark Bonus Code - Juni 2024

description: Slotpark Bonus Codes sind Promotion-Codes, die Spieler verwenden können, um spezielle Boni und Belohnungen im Slotpark Handyspiel zu erhalten.

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      changefreq: "daily"
      priority: 0.5

sitemap:
  exclude: ["404.html"]
  include_posts: false
  changefreq: "daily"
  priority: 0.5
